#!/bin/bash
source scripts/env.sh

rm *.tgz 2>/dev/null
echo "Building tar"
npm pack
echo "Uploading and installing deps"
cat jellobot-*.tgz | ssh "$ssh_host"  'su - jellobot -c "cd /home/jellobot; tar -xz; cd package; source ~/.nvm/nvm.sh; nvm use 6; ~/.yarn/bin/yarn"'
rm *.tgz 2>/dev/null
echo "Done"
echo "Run ./scripts/restart to restart the process"

