#!/bin/bash

curl -sSL --compressed http://boshi.inimino.org/ecmabot-factoids.json > src/plugins/factoids/facts.json

printf "Total factoids: %d\n" "$(jq '.factoids | keys | length' < src/plugins/factoids/facts.json)"

